version: '2.2'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
    logging:
      driver: local
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - grafana-storage:/var/lib/grafana
    restart: always
    logging:
      driver: local

  redis_exporter:
    image: oliver006/redis_exporter
    container_name: redis_exporter
    ports:
      - 9121:9121

volumes:
    grafana-storage:
