# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "z370n_jvm"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["10.255.2.1:12345", "10.255.2.13:12345", "10.255.2.230:12345", "10.255.2.231:12345",  "10.255.2.232:12345",  "10.255.2.233:12345",  "10.255.2.234:12345",  "10.255.2.235:12345", "10.255.2.246:12345"]

  - job_name: "z370n_nodes"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["10.255.2.12:9100", "10.255.2.13:9100", "10.255.2.14:9100", "10.255.2.15:9100", "10.255.2.16:9100","10.255.2.10:9100", "10.255.2.1:9100"]

  - job_name: "nuc8_nodes"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["10.255.4.1:9100"]
      - targets: ["10.255.3.10:9100", "10.255.3.11:9100", "10.255.3.12:9100", "10.255.3.13:9100", "10.255.3.14:9100", "10.255.3.15:9100", "10.255.3.16:9100"]
      - targets: ["10.255.4.10:9100", "10.255.4.11:9100", "10.255.4.12:9100", "10.255.4.13:9100", "10.255.4.14:9100", "10.255.4.15:9100", "10.255.4.16:9100"]

  - job_name: "nuc8_jvm"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["10.255.3.230:12345", "10.255.3.231:12345"]

  - job_name: "dellr730_nodes"
    static_configs:
      - targets: ["10.255.1.12:9100", "10.255.1.13:9100", "10.255.1.14:9100", "10.255.1.15:9100", "10.255.1.16:9100"]
      - targets: ["10.255.1.17:9100", "10.255.1.18:9100", "10.255.1.19:9100", "10.255.1.20:9100"]
      - targets: ["10.255.1.31:9100", "10.255.1.32:9100", "10.255.1.33:9100", "10.255.1.34:9100"]
      - targets: ["10.255.1.41:9100", "10.255.1.42:9100", "10.255.1.43:9100", "10.255.1.44:9100"]

  - job_name: "dellr730_jvm"
    static_configs:
      - targets: ["10.255.1.12:12345", "10.255.1.13:12345", "10.255.1.14:12345", "10.255.1.15:12345", "10.255.1.100:12345", "10.255.1.140:12345"]

  - job_name: "mbp156"
    static_configs:
      - targets: ["mbp156:9001"]

  - job_name: "consul_sd"
    consul_sd_configs:
      - server: '10.255.4.15:8500'
        services: ["mqtt_client", "20220706", "node-exporter"]

  - job_name: elasticsearch_exporter
    static_configs:
      - targets: ["10.255.4.15:9114"]


  # redis_exporter
  ## config for the multiple Redis targets that the exporter will scrape
  - job_name: 'redis_exporter_targets_2'
    static_configs:
      - targets:
        - redis://10.255.1.42:7000
        - redis://10.255.1.42:7000
        - redis://10.255.1.42:7001
        - redis://10.255.1.42:7002
        - redis://10.255.1.42:7003
        - redis://10.255.1.42:7004
        - redis://10.255.1.42:7005
        - redis://10.255.1.42:7006
        - redis://10.255.1.42:7007
        - redis://10.255.1.42:7008
        - redis://10.255.1.42:7009
        - redis://10.255.1.42:7010
        - redis://10.255.1.42:7011
        - redis://10.255.1.41:7000
        - redis://10.255.1.41:7001
        - redis://10.255.1.41:7002
        - redis://10.255.1.41:7003
        - redis://10.255.1.41:7004
        - redis://10.255.1.41:7005
        - redis://10.255.1.41:7006
        - redis://10.255.1.41:7007
        - redis://10.255.1.41:7008
        - redis://10.255.1.41:7009
        - redis://10.255.1.41:7010
        - redis://10.255.1.41:7011
        - redis://10.255.1.43:7000
        - redis://10.255.1.43:7001
        - redis://10.255.1.43:7002
        - redis://10.255.1.43:7003
        - redis://10.255.1.43:7004
        - redis://10.255.1.43:7005
        - redis://10.255.1.43:7006
        - redis://10.255.1.43:7007
        - redis://10.255.1.43:7008
        - redis://10.255.1.43:7009
        - redis://10.255.1.43:7010
        - redis://10.255.1.43:7011

    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: redis_exporter:9121

  # redis_exporter
  ## config for the multiple Redis targets that the exporter will scrape
  - job_name: 'redis_exporter_targets'
    static_configs:
      - targets:
        - redis://10.255.4.15:7000
        - redis://10.255.4.15:7001
        - redis://10.255.4.15:7002
        - redis://10.255.4.15:7003
        - redis://10.255.4.15:7004
        - redis://10.255.4.15:7005
        - redis://10.255.4.15:7006
        - redis://10.255.4.15:7007
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: redis_exporter:9121

  ## config for scraping the exporter itself
  - job_name: 'redis_exporter'
    static_configs:
      - targets:
        - redis_exporter:9121
